### ISSUE TITLE
change the mouse pointer ? 

### ISSUE THREAD

**Issue by 12rambau** [sphinx-contrib/images#28]
At the moment when I hover an image the mouse pointer change from normal pointer to link pointer. Which according to me is confusing to the end user. Is it possible to customize it to zoom-in ?

**Comment by jonascj** [comment]
Thank you for your question and possible suggestion for improvement.

If I hover over any of the images (produced by the thumbnail directive) in the documentation https://sphinxcontrib-images.readthedocs.io/en/latest/ I see a change in pointer as you describe, from the normal pointer to the pointer used for links.

That is because the images are wrapped in a anchor/link tag (`<a href= ... ></a>`). So it is a link the user is hovering over.

As far as I know that is how lightbox works, the library/script/project we use to make image overlay / popup. All the examples and descriptions here https://lokeshdhakar.com/projects/lightbox2/ mention how lightbox works with links to images. 

You could write yourself a bit of custom css to change the pointer:
 - https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html
 - https://www.w3schools.com/csSref/tryit.asp?filename=trycss_cursor

**Comment by 12rambau** [comment]
thanks for the tip I'll see what I can implement in my doc !

**Comment by jonascj** [comment]
You're welcome.

**Comment by 12rambau** [comment]
for the record, that was as simple as that 

```css
/*********************************************************************************
*   change the lightbox cursor
*
**/
a[data-lightbox] {cursor: zoom-in;}
```
